// Package {{module_name}} — {{module_description}}
// Auto-generated by bootstrap.sh
package {{module_name}}

import (
	"errors"
)
{{imports_block}}
// {{description}}
type {{component_name}} struct {
{{struct_fields}}
	Optional bool
}

// Name 用于注册中心识别
const Name{{component_name}} = "{{component_name}}"

// New 构造一个 {{component_name}} 实例
func New{{component_name}}() *{{component_name}} {
	return &{{component_name}}{Optional: {{optional_go}}}
}
{{todos_block}}
// Call 执行 {{component_name}} 的核心逻辑
func (c *{{component_name}}) Call() (interface{}, error) {
	return nil, errors.New("{{component_name}}.Call() 待实现")
}
