#!/usr/bin/env bash
set -euo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="."
STRUCT="${STRUCT_FILE:-./struct.json}"
OUT="generated/intelligence/dynamic-surfaces.json"
JSON_OUT=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root) ROOT="$2"; shift 2 ;;
    --struct|-s) STRUCT="$2"; shift 2 ;;
    --output|-o) OUT="$2"; shift 2 ;;
    --json) JSON_OUT=1; shift ;;
    -h|--help) echo "dynamic_surface_scan.sh --root <repo> --struct <struct> [--output <file>] [--json]"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 64 ;;
  esac
done

command -v jq >/dev/null 2>&1 || { echo "[FAIL] missing jq" >&2; exit 2; }
[[ -d "$ROOT" && -f "$STRUCT" ]] || { echo "[FAIL] missing root or struct" >&2; exit 2; }
ROOT="$(cd "$ROOT" && pwd)"
STRUCT="$(cd "$(dirname "$STRUCT")" && pwd)/$(basename "$STRUCT")"
mkdir -p "$(dirname "$OUT")"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
framework_file="$tmp/framework.json"
extra_file="$tmp/extra.json"
bash "$SELF_DIR/dynamic_framework_resolvers.sh" --root "$ROOT" --struct "$STRUCT" --json > "$framework_file"

python3 - "$ROOT" "$STRUCT" > "$extra_file" <<'PY'
import hashlib
import json
import os
import re
import sys

root, struct_path = sys.argv[1], sys.argv[2]
with open(struct_path, encoding="utf-8") as f:
    struct = json.load(f)
components = {}
for mod in struct.get("modules", []):
    for comp in mod.get("components", []):
        rel = comp.get("path") or ""
        if rel:
            components[os.path.normpath(rel)] = {"module": mod.get("name", ""), "component": comp.get("name", "")}

def comp_for(rel):
    rel = os.path.normpath(rel)
    return components.get(rel, {"module": "", "component": ""})

def sid(kind, name, rel, line):
    return re.sub(r"[^A-Za-z0-9_.:-]", "_", f"{kind}:{name}:{rel}:{line}")[:180]

def h(*parts):
    return hashlib.sha256(":".join(map(str, parts)).encode()).hexdigest()

def node(kind, name, rel, line, resolver, conf, risk, evidence):
    c = comp_for(rel)
    return {
        "id": sid(kind, name, rel, line),
        "kind": kind,
        "name": name,
        "path": rel,
        "line": int(line),
        "module": c["module"],
        "component": c["component"],
        "resolver": resolver,
        "confidence": conf,
        "risk_level": risk,
        "verification_status": "unsafe" if risk == "dynamic_unsafe" else ("probe_gap" if risk == "dynamic_unverified" else "static_inferred"),
        "semantic_links": [],
        "evidence": evidence,
        "hash": h(kind, name, rel, line, resolver),
    }

nodes = []
skip = {".git", "node_modules", "target", "dist", "build", ".venv", "__pycache__"}
for dirpath, dirnames, filenames in os.walk(root):
    rel_dir = os.path.relpath(dirpath, root)
    if rel_dir == "generated":
        dirnames[:] = []
        continue
    dirnames[:] = [d for d in dirnames if d not in skip]
    for filename in filenames:
        path = os.path.join(dirpath, filename)
        rel = os.path.relpath(path, root)
        ext = os.path.splitext(filename)[1]
        try:
            if os.path.getsize(path) > 1024 * 1024:
                continue
            text = open(path, encoding="utf-8", errors="ignore").read()
        except OSError:
            continue
        lines = text.splitlines()
        generated_reason = None
        if re.search(r"(?i)@generated|code generated|do not edit|auto-generated|generated by", text[:2000]):
            generated_reason = "header"
        if re.search(r"(^|/)(generated|gen|__generated__|openapi|graphql|protobuf|proto|prisma|dist|build)/", rel):
            generated_reason = generated_reason or "path"
        if generated_reason:
            contract = ""
            for candidate in ("openapi.json", "openapi.yaml", "schema.graphql", "schema.proto", "proto"):
                if candidate in rel.lower() or candidate in text[:2000].lower():
                    contract = candidate
                    break
            nodes.append(node("generated_interface", rel, rel, 1, "generated_code_provenance", 0.84, "dynamic_unverified", {"reason": generated_reason, "source_contract_hint": contract}))

        for idx, line in enumerate(lines, 1):
            env_patterns = [
                r"os\.environ(?:\.get)?\(\s*['\"]([^'\"]+)",
                r"process\.env\.([A-Za-z_][A-Za-z0-9_]*)",
                r"process\.env\[['\"]([^'\"]+)",
                r"os\.Getenv\(\s*['\"]([^'\"]+)",
                r"env::var\(\s*['\"]([^'\"]+)",
                r"config\.(?:get|require)\(\s*['\"]([^'\"]+)"
            ]
            for pat in env_patterns:
                m = re.search(pat, line)
                if m:
                    key = m.group(1)
                    nodes.append(node("env_gate", key, rel, idx, "env_feature_flag_scan", 0.78, "dynamic_unverified", {"line": line.strip(), "default_documented": ("default" in line.lower() or "??" in line or "||" in line)}))
            if re.search(r"\b(featureFlag|flags|launchDarkly|unleash)\b", line, re.I):
                nodes.append(node("config_gate", line.strip()[:80], rel, idx, "feature_flag_scan", 0.67, "dynamic_unverified", {"line": line.strip()}))
print(json.dumps(nodes, sort_keys=True))
PY

report=$(jq -n \
  --arg root "$ROOT" \
  --arg struct "$STRUCT" \
  --arg generated_at "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
  --slurpfile framework_file "$framework_file" \
  --slurpfile extra_file "$extra_file" '
  ($framework_file[0] // {nodes:[]}) as $framework
  | ($extra_file[0] // []) as $extra
  |
  (($framework.nodes // []) + $extra) as $raw
  | ($raw | unique_by(.id) | sort_by(.path,.line,.kind,.name)) as $nodes
  | {
      schema_version:"1.0",
      ok:true,
      generated_at:$generated_at,
      root:$root,
      struct:$struct,
      summary:{
        nodes:($nodes|length),
        routes:($nodes|map(select(.kind=="route"))|length),
        di_bindings:($nodes|map(select(.kind=="di_binding"))|length),
        plugin_registrations:($nodes|map(select(.kind=="plugin_registration"))|length),
        event_subscriptions:($nodes|map(select(.kind=="event_subscription"))|length),
        dynamic_imports:($nodes|map(select(.kind=="dynamic_import"))|length),
        generated_files:($nodes|map(select(.kind=="generated_interface"))|length),
        env_keys:($nodes|map(select(.kind=="env_gate"))|length),
        dynamic_known:($nodes|map(select(.risk_level=="dynamic_known"))|length),
        dynamic_observed:($nodes|map(select(.risk_level=="dynamic_observed"))|length),
        dynamic_unverified:($nodes|map(select(.risk_level=="dynamic_unverified"))|length),
        dynamic_unsafe:($nodes|map(select(.risk_level=="dynamic_unsafe"))|length)
      },
      nodes:$nodes,
      probe_recommendations:(
        $nodes
        | map(select(.verification_status=="probe_gap" or .risk_level=="dynamic_unsafe"))
        | map({node_id:.id, command:"simple_model_pi.sh runtime-probe --execute --json", reason:("confirm " + .kind + " " + .name)})
      )
    }')

printf '%s\n' "$report" > "$OUT"
if [[ "$JSON_OUT" == "1" ]]; then printf '%s\n' "$report"; else jq -r '"Dynamic Surfaces nodes=" + (.summary.nodes|tostring) + " unsafe=" + (.summary.dynamic_unsafe|tostring) + " output='"$OUT"'"' <<<"$report"; fi
