#!/usr/bin/env bash
# generators/go.sh — Go 代码骨架生成器（纯 bash + jq）
# 约定: PascalCase -> snake_case 文件，类型 + 方法
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"

LANG="go"
LANG_DIR="${OUTPUT_DIR}/${LANG}"
mkdir -p "$LANG_DIR"

# PascalCase -> snake_case
to_snake() {
    python3 -c "import sys,re; n=sys.argv[1]; s=re.sub(r'(.)([A-Z][a-z]+)', r'\1_\2', n); print(re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', s).lower())" "$1"
}

# 每个 module -> 包目录
PACKAGE_NAME=$(basename "$LANG_DIR" | tr '[:upper:]' '[:lower:]')

for mi in $(seq 0 $(($(jq '.modules | length' "$STRUCT_FILE") - 1))); do
    m_name=$(jq -r ".modules[$mi].name" "$STRUCT_FILE")
    m_desc=$(jq -r ".modules[$mi].description" "$STRUCT_FILE")
    m_dir="${LANG_DIR}/${m_name}"
    mkdir -p "$m_dir"

    # 每个 component 一个文件
    cc=$(jq ".modules[$mi].components | length" "$STRUCT_FILE")
    for ci in $(seq 0 $((cc - 1))); do
        c_name=$(jq -r ".modules[$mi].components[$ci].name" "$STRUCT_FILE")
        c_desc=$(jq -r ".modules[$mi].components[$ci].description" "$STRUCT_FILE")
        c_exports=$(jq -c ".modules[$mi].components[$ci].exports // []" "$STRUCT_FILE")
        c_imports=$(jq -c ".modules[$mi].components[$ci].imports // .modules[$mi].components[$ci].depends_on // []" "$STRUCT_FILE")
        c_optional=$(jq -r ".modules[$mi].components[$ci].optional // false" "$STRUCT_FILE")
        c_todos=$(jq -c ".modules[$mi].components[$ci].todos // []" "$STRUCT_FILE")
        snake=$(to_snake "$c_name")
        file="${m_dir}/${snake}.go"

        if should_regenerate "$file" "$STRUCT_FILE"; then
            # Go struct 字段
            struct_fields=""
            while IFS= read -r e; do
                [[ -z "$e" ]] && continue
                struct_fields+=$'\t'"${e} interface{} // ${e}"$'\n'
            done < <(echo "$c_exports" | jq -r '.[]')

            # imports — Go 用同包内 import 路径
            imports_block=""
            seen_pkgs=""
            while IFS= read -r dep; do
                [[ -z "$dep" ]] && continue
                dep_module=$(module_of "$dep")
                [[ -z "$dep_module" ]] && continue
                if [[ "$dep_module" != "$m_name" ]] && [[ "$seen_pkgs" != *"|$dep_module|"* ]]; then
                    imports_block+=$'\t'"\"${PROJECT_NAME:-app}/${dep_module}\""$'\n'
                    seen_pkgs+="|${dep_module}|"
                fi
            done < <(echo "$c_imports" | jq -r '.[]')

            # todos 注释
            todo_block=""
            if [[ "$(echo "$c_todos" | jq 'length')" -gt 0 ]]; then
                todo_block="// TODO:"$'\n'
                while IFS= read -r line; do
                    [[ -z "$line" ]] && continue
                    todo_block+="//   - ${line}"$'\n'
                done < <(echo "$c_todos" | jq -r '.[] | "\(.id): \(.task) [priority=\(.priority // "medium")] blocks=\(.blocks // [])"')
            fi

            {
                echo "// Package ${m_name} — ${m_desc}"
                echo "// Auto-generated by bootstrap.sh"
                echo "package ${m_name}"
                echo ""
                echo "import ("
                echo "	\"errors\""
                [[ -n "$imports_block" ]] && echo "$imports_block"
                echo ")"
                echo ""
                echo "// ${c_desc}"
                echo "type ${c_name} struct {"
                [[ -n "$struct_fields" ]] && echo "$struct_fields"
                echo "	Optional bool"
                echo "}"
                echo ""
                echo "// Name 用于注册中心识别"
                echo "const Name${c_name} = \"${c_name}\""
                echo ""
                echo "// New 构造一个 ${c_name} 实例"
                echo "func New${c_name}() *${c_name} {"
                echo "	return &${c_name}{Optional: ${c_optional}}"
                echo "}"
                echo ""
                [[ -n "$todo_block" ]] && echo "$todo_block"
                echo "// Call 执行 ${c_name} 的核心逻辑"
                echo "func (c *${c_name}) Call() (interface{}, error) {"
                echo "	return nil, errors.New(\"${c_name}.Call() 待实现\")"
                echo "}"
            } > "$file"
            mark_generated "$file" "$STRUCT_FILE"
            say "  [OK] go: ${m_name}/${snake}.go"
        else
            say "  [SKIP] go: ${m_name}/${snake}.go (unchanged)"
        fi
    done

    # per-module todo.json
    if [[ "$(jq "[.modules[$mi].components[].todos // [] | length] | add // 0" "$STRUCT_FILE")" -gt 0 ]]; then
        todo_file="${m_dir}/todo.json"
        if should_regenerate "$todo_file" "$STRUCT_FILE"; then
            jq "{module: .modules[$mi].name, description: .modules[$mi].description, todos: [.modules[$mi].components[] | . as \$c | .todos[]? | . + {component: \$c.name}]}" "$STRUCT_FILE" \
                > "$todo_file"
            mark_generated "$todo_file" "$STRUCT_FILE"
            say "  [OK] go: ${m_name}/todo.json"
        else
            say "  [SKIP] go: ${m_name}/todo.json (unchanged)"
        fi
    fi
done

# go.mod
GO_MOD="${LANG_DIR}/go.mod"
if should_regenerate "$GO_MOD" "$STRUCT_FILE"; then
    cat > "$GO_MOD" <<MOD
module ${PROJECT_NAME:-app}

go 1.22
MOD
    mark_generated "$GO_MOD" "$STRUCT_FILE"
    say "  [OK] go: go.mod"
else
    say "  [SKIP] go: go.mod (unchanged)"
fi

echo "  [OK] go 生成完成: $LANG_DIR/"