#!/usr/bin/env bash
# generators/python.sh — Python 代码骨架生成器（纯 bash + jq）
# 约定: PascalCase 组件 -> snake_case 文件，class 封装
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"

LANG="python"
LANG_DIR="${OUTPUT_DIR}/${LANG}"
mkdir -p "$LANG_DIR"

# PascalCase -> snake_case
to_snake() {
    python3 -c "import sys,re; n=sys.argv[1]; s=re.sub(r'(.)([A-Z][a-z]+)', r'\1_\2', n); print(re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', s).lower())" "$1"
}

# 把 JSON 字符串数组 -> Python list literal
to_py_list() {
    jq -c '.' <<<"$1" | sed "s/^\[//; s/\]$//; s/^\"//; s/\"$//"
}

# 每个 module 的处理（用变量避免 zsh 的 {} 冲突）
N_MODULES=$(jq '.modules // [] | length' "$STRUCT_FILE")
for mi in $(seq 0 $((N_MODULES - 1))); do
    module_json=$(read_module "$mi")
    module_name=$(echo "$module_json" | jq -r '.name')
    module_lang=$(echo "$module_json" | jq -r '.language')
    module_desc=$(echo "$module_json" | jq -r '.description')

    # per-module language 过滤
    if [[ "$module_lang" != "any" && "$module_lang" != "$LANG" ]]; then
        say "跳过 ${module_name}（language=${module_lang}，不是 ${LANG}）"
        continue
    fi

    module_dir="${LANG_DIR}/${module_name}"
    mkdir -p "$module_dir"

    # __init__.py
    init_py="${module_dir}/__init__.py"
    if should_regenerate "$init_py" "$STRUCT_FILE"; then
        {
            echo "\"\"\"Module: ${module_name}"
            echo ""
            echo "${module_desc}"
            echo "\"\"\""
        } > "$init_py"
        mark_generated "$init_py" "$STRUCT_FILE"
        say "  [OK] ${LANG_DIR#$OUTPUT_DIR/}/${module_name}/__init__.py"
    else
        say "  [SKIP] ${LANG_DIR#$OUTPUT_DIR/}/${module_name}/__init__.py (unchanged)"
    fi

    # 每个 component 生成文件
    component_count=$(jq ".modules[$mi].components | length" "$STRUCT_FILE")
    for ci in $(seq 0 $((component_count - 1))); do
        c_name=$(jq -r ".modules[$mi].components[$ci].name" "$STRUCT_FILE")
        c_desc=$(jq -r ".modules[$mi].components[$ci].description" "$STRUCT_FILE")
        c_exports=$(jq -c ".modules[$mi].components[$ci].exports // []" "$STRUCT_FILE")
        c_imports=$(jq -c ".modules[$mi].components[$ci].imports // .modules[$mi].components[$ci].depends_on // []" "$STRUCT_FILE")
        c_optional=$(jq -r ".modules[$mi].components[$ci].optional // false" "$STRUCT_FILE")
        c_todos_json=$(jq -c ".modules[$mi].components[$ci].todos // []" "$STRUCT_FILE")

        snake=$(to_snake "$c_name")
        file="${module_dir}/${snake}.py"

        if should_regenerate "$file" "$STRUCT_FILE"; then
            # optional 转换成 Python bool
            if [[ "$c_optional" == "true" ]]; then
                optional_py="True"
            else
                optional_py="False"
            fi

            # 构建 import 块
            imports_block=""
            while IFS= read -r dep; do
                [[ -z "$dep" ]] && continue
                dep_module=$(module_of "$dep")
                [[ -z "$dep_module" ]] && continue
                dep_snake=$(to_snake "$dep")
                if [[ "$dep_module" == "$module_name" ]]; then
                    imports_block+="from .${dep_snake} import ${dep}"$'\n'
                else
                    imports_block+="from ..${dep_module}.${dep_snake} import ${dep}"$'\n'
                fi
            done < <(echo "$c_imports" | jq -r '.[]')

            # produces list literal
            exports_py=$(echo "$c_exports" | jq -r '. | tostring')
            imports_py=$(echo "$c_imports" | jq -r '. | tostring')

            # todos 注释
            todos_block=""
            if [[ "$(echo "$c_todos_json" | jq 'length')" -gt 0 ]]; then
                todos_block="    # TODO:"$'\n'
                while IFS= read -r line; do
                    [[ -z "$line" ]] && continue
                    todos_block+="    #   - ${line}"$'\n'
                done < <(echo "$c_todos_json" | jq -r '.[] | "\(.id): \(.task) [priority=\(.priority // "medium")] [\(.status // "pending")] blocks=\(.blocks // [])"')
            fi

            {
                echo "\"\"\"Component: ${c_name} (module: ${module_name})"
                echo ""
                echo "${c_desc}"
                echo ""
                echo "Auto-generated by bootstrap.sh — implement __call__()."
                echo "\"\"\""
                echo "from typing import Any, List"
                echo "${imports_block}from ..base import Service as _BaseComponent"
                echo ""
                echo ""
                echo "class ${c_name}(_BaseComponent):"
                echo "    \"\"\"${c_desc}\"\"\""
                echo ""
                echo "    name: str = \"${c_name}\""
                echo "    exports: List[str] = ${exports_py}"
                echo "    imports: List[str] = ${imports_py}"
                echo "    optional: bool = ${optional_py}"
                echo ""
                [[ -n "$todos_block" ]] && echo "$todos_block"
                echo "    def __call__(self) -> Any:"
                echo "        \"\"\"执行 ${c_name} 的核心逻辑\"\"\""
                echo "        raise NotImplementedError(\"${c_name}.__call__() 待实现\")"
            } > "$file"
            mark_generated "$file" "$STRUCT_FILE"
            say "  [OK] ${module_name}/${snake}.py"
        else
            say "  [SKIP] ${module_name}/${snake}.py (unchanged)"
        fi
    done

    # per-module todo.json（如果有 todo 的话）
    if [[ "$(jq "[.modules[$mi].components[].todos // [] | length] | add // 0" "$STRUCT_FILE")" -gt 0 ]]; then
        todo_file="${module_dir}/todo.json"
        if should_regenerate "$todo_file" "$STRUCT_FILE"; then
            jq "{module: .modules[$mi].name, description: .modules[$mi].description, todos: [.modules[$mi].components[] | . as \$c | .todos[]? | . + {component: \$c.name}]}" "$STRUCT_FILE" \
                > "$todo_file"
            mark_generated "$todo_file" "$STRUCT_FILE"
            say "  [OK] ${module_name}/todo.json"
        else
            say "  [SKIP] ${module_name}/todo.json (unchanged)"
        fi
    fi
done

# 顶层 base.py
mkdir -p "$LANG_DIR"
BASE_PY="${LANG_DIR}/base.py"
if should_regenerate "$BASE_PY" "$STRUCT_FILE"; then
    cat > "$BASE_PY" <<'PY'
"""Auto-generated base — do not edit, rerun bootstrap.sh"""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Type


@dataclass
class Service(ABC):
    """所有 component 的抽象基类"""
    name: str = ""
    exports: List[str] = field(default_factory=list)
    imports: List[str] = field(default_factory=list)
    optional: bool = False

    @abstractmethod
    def __call__(self) -> Any:
        raise NotImplementedError(f"{self.__class__.__name__}.__call__() 未实现")


class Registry:
    _r: Dict[str, Type[Service]] = {}
    @classmethod
    def register(cls, c): cls._r[c.name] = c; return c
    @classmethod
    def get(cls, n): return cls._r.get(n)
    @classmethod
    def all(cls): return dict(cls._r)
PY
    mark_generated "$BASE_PY" "$STRUCT_FILE"
    say "  [OK] base.py"
else
    say "  [SKIP] base.py (unchanged)"
fi

echo "  [OK] python 生成完成: $LANG_DIR/"