#!/usr/bin/env bash
# generators/rust.sh — Rust 代码骨架生成器（纯 bash + jq）
# 约定: 每个 module -> 子模块 (mod.rs), 每个 component -> pub struct + impl
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"

LANG="rust"
LANG_DIR="${OUTPUT_DIR}/${LANG}"
mkdir -p "$LANG_DIR/src"

# PascalCase -> snake_case
to_snake() {
    python3 -c "import sys,re; n=sys.argv[1]; s=re.sub(r'(.)([A-Z][a-z]+)', r'\1_\2', n); print(re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', s).lower())" "$1"
}

# PascalCase -> SCREAMING_SNAKE_CASE
to_screaming() {
    echo "$(to_snake "$1" | tr '[:lower:]' '[:upper:]')"
}

# JSON 字符串数组 -> Rust Vec<String> 字面量
to_rust_str_vec() {
    local arr="$1"
    if [[ "$arr" == "[]" ]]; then echo "Vec::new()"; return; fi
    local items=""
    while IFS= read -r s; do
        [[ -z "$s" ]] && continue
        items+="        String::from(\"$s\"),"$'\n'
    done < <(echo "$arr" | jq -r '.[]')
    echo "vec!["$'\n'"${items}    ]"
}

# 每个 module -> src/<module>/mod.rs
for mi in $(seq 0 $(($(jq '.modules | length' "$STRUCT_FILE") - 1))); do
    m_name=$(jq -r ".modules[$mi].name" "$STRUCT_FILE")
    m_desc=$(jq -r ".modules[$mi].description" "$STRUCT_FILE")
    m_dir="${LANG_DIR}/src/${m_name}"
    mkdir -p "$m_dir"

    # mod.rs 头（写一次，后续 component 循环追加 pub mod / pub use / tests）
    # mod.rs 内容随 component 列表变化而变化，因此总是重新生成
    {
        echo "//! Module: ${m_name}"
        echo "//!"
        echo "//! ${m_desc}"
        echo ""
        echo "// Auto-generated by bootstrap.sh"
    } > "${m_dir}/mod.rs"

    # 每个 component -> pub struct + impl block
    cc=$(jq ".modules[$mi].components | length" "$STRUCT_FILE")
    for ci in $(seq 0 $((cc - 1))); do
        c_name=$(jq -r ".modules[$mi].components[$ci].name" "$STRUCT_FILE")
        c_desc=$(jq -r ".modules[$mi].components[$ci].description" "$STRUCT_FILE")
        c_exports=$(jq -c ".modules[$mi].components[$ci].exports // []" "$STRUCT_FILE")
        c_imports=$(jq -c ".modules[$mi].components[$ci].imports // .modules[$mi].components[$ci].depends_on // []" "$STRUCT_FILE")
        c_optional=$(jq -r ".modules[$mi].components[$ci].optional // false" "$STRUCT_FILE")
        c_todos=$(jq -c ".modules[$mi].components[$ci].todos // []" "$STRUCT_FILE")
        snake=$(to_snake "$c_name")
        file="${m_dir}/${snake}.rs"

        if should_regenerate "$file" "$STRUCT_FILE"; then
            exports_rust=$(to_rust_str_vec "$c_exports")
            imports_rust=$(to_rust_str_vec "$c_imports")

            # use 块: 同模块用 super::, 跨模块用 crate::
            use_block=""
            while IFS= read -r dep; do
                [[ -z "$dep" ]] && continue
                dep_module=$(module_of "$dep")
                [[ -z "$dep_module" ]] && continue
                dep_snake=$(to_snake "$dep")
                if [[ "$dep_module" == "$m_name" ]]; then
                    use_block+="use super::${dep_snake}::${dep};"$'\n'
                else
                    use_block+="use crate::${dep_module}::${dep_snake}::${dep};"$'\n'
                fi
            done < <(echo "$c_imports" | jq -r '.[]')

            # struct fields from exports
            struct_fields=""
            while IFS= read -r e; do
                [[ -z "$e" ]] && continue
                struct_fields+="    pub ${e}: Option<String>,  // ${e}"$'\n'
            done < <(echo "$c_exports" | jq -r '.[]')

            # todos 注释
            todo_lines=""
            if [[ "$(echo "$c_todos" | jq 'length')" -gt 0 ]]; then
                todo_lines="    // TODO:"$'\n'
                while IFS= read -r line; do
                    [[ -z "$line" ]] && continue
                    todo_lines+="    //   - ${line}"$'\n'
                done < <(echo "$c_todos" | jq -r '.[] | "\(.id): \(.task) [priority=\(.priority // "medium")] blocks=\(.blocks // [])"')
            fi

            {
                echo "//! Component: ${c_name}"
                echo "//!"
                echo "//! ${c_desc}"
                echo ""
                echo "use serde::{Deserialize, Serialize};"
                echo "use std::any::Any;"
                echo "${use_block}"
                echo "/// ${c_desc}"
                echo "#[derive(Debug, Clone, Serialize, Deserialize)]"
                echo "pub struct ${c_name} {"
                [[ -n "$struct_fields" ]] && echo "$struct_fields"
                echo "    pub optional: bool,"
                echo "}"
                echo ""
                echo "pub const NAME: &str = \"${c_name}\";"
                # 修正: 空 exports 时使用 &[]，否则 &["a", "b"]
                if [[ "$(echo "$c_exports" | jq 'length')" -eq 0 ]]; then
                    echo "pub const EXPORTS: &[&str] = &[];"
                else
                    _items=$(echo "$c_exports" | jq -r 'map("\"" + . + "\"") | join(", ")')
                    echo "pub const EXPORTS: &[&str] = &[${_items}];"
                fi
                echo ""
                [[ -n "$todo_lines" ]] && echo "$todo_lines"
                echo "impl ${c_name} {"
                echo "    pub fn new() -> Self {"
                echo "        Self {"
                # 给每个 export 字段初始化
                while IFS= read -r e; do
                    [[ -z "$e" ]] && continue
                    echo "            ${e}: None,"
                done < <(echo "$c_exports" | jq -r '.[]')
                echo "            optional: ${c_optional},"
                echo "        }"
                echo "    }"
                echo ""
                echo "    /// 执行 ${c_name} 的核心逻辑"
                echo "    pub fn call(&self) -> Box<dyn Any> {"
                echo "        unimplemented!(\"${c_name}::call() 待实现\")"
                echo "    }"
                echo "}"
                echo ""
                echo "impl Default for ${c_name} {"
                echo "    fn default() -> Self { Self::new() }"
                echo "}"
            } > "$file"
            mark_generated "$file" "$STRUCT_FILE"
            say "  [OK] rust: ${m_name}/${snake}.rs"
        else
            say "  [SKIP] rust: ${m_name}/${snake}.rs (unchanged)"
        fi
    done

    # per-module todo.json
    if [[ "$(jq "[.modules[$mi].components[].todos // [] | length] | add // 0" "$STRUCT_FILE")" -gt 0 ]]; then
        todo_file="${m_dir}/todo.json"
        if should_regenerate "$todo_file" "$STRUCT_FILE"; then
            jq "{module: .modules[$mi].name, description: .modules[$mi].description, todos: [.modules[$mi].components[] | . as \$c | .todos[]? | . + {component: \$c.name}]}" "$STRUCT_FILE" \
                > "$todo_file"
            mark_generated "$todo_file" "$STRUCT_FILE"
            say "  [OK] rust: ${m_name}/todo.json"
        else
            say "  [SKIP] rust: ${m_name}/todo.json (unchanged)"
        fi
    fi

    # 在 mod.rs 加 use + pub mod（mod.rs 头部已写，下面追加）
    # mod.rs 是聚合文件，总是重新生成（依赖 component 列表）
    echo "" >> "${m_dir}/mod.rs"
    cc=$(jq ".modules[$mi].components | length" "$STRUCT_FILE")
    for ci in $(seq 0 $((cc - 1))); do
        c_name=$(jq -r ".modules[$mi].components[$ci].name" "$STRUCT_FILE")
        snake=$(to_snake "$c_name")
        echo "pub mod ${snake};" >> "${m_dir}/mod.rs"
        echo "pub use ${snake}::${c_name};" >> "${m_dir}/mod.rs"
    done
done

# Cargo.toml
CRATE_NAME=$(basename "$LANG_DIR" | tr '[:upper:]' '[:lower:]' | tr - _)
CARGO_FILE="${LANG_DIR}/Cargo.toml"
if should_regenerate "$CARGO_FILE" "$STRUCT_FILE"; then
    cat > "$CARGO_FILE" <<TOML
[package]
name = "${CRATE_NAME}"
version = "0.1.0"
edition = "2021"

[lib]
name = "${CRATE_NAME}"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
TOML
    mark_generated "$CARGO_FILE" "$STRUCT_FILE"
    say "  [OK] rust: Cargo.toml"
else
    say "  [SKIP] rust: Cargo.toml (unchanged)"
fi

# src/lib.rs: 把所有 module 串起来
LIB_RS="${LANG_DIR}/src/lib.rs"
if should_regenerate "$LIB_RS" "$STRUCT_FILE"; then
    {
        echo "//! ${CRATE_NAME} — 自动生成的库入口"
        echo "//! Auto-generated by bootstrap.sh"
        echo ""
        for mi in $(seq 0 $(($(jq '.modules | length' "$STRUCT_FILE") - 1))); do
            m_name=$(jq -r ".modules[$mi].name" "$STRUCT_FILE")
            echo "pub mod ${m_name};"
        done
    } > "$LIB_RS"
    mark_generated "$LIB_RS" "$STRUCT_FILE"
    say "  [OK] rust: src/lib.rs"
else
    say "  [SKIP] rust: src/lib.rs (unchanged)"
fi

# 每个 module 生成一个最小 smoke test（内联到 mod.rs 的 #[cfg(test)] 块）
for mi in $(seq 0 $(($(jq '.modules | length' "$STRUCT_FILE") - 1))); do
    m_name=$(jq -r ".modules[$mi].name" "$STRUCT_FILE")
    m_dir="${LANG_DIR}/src/${m_name}"
    cc=$(jq ".modules[$mi].components | length" "$STRUCT_FILE")
    {
        echo ""
        echo "#[cfg(test)]"
        echo "mod tests {"
        for ci in $(seq 0 $((cc - 1))); do
            c_name=$(jq -r ".modules[$mi].components[$ci].name" "$STRUCT_FILE")
            snake=$(to_snake "$c_name")
            echo "    use super::${snake}::${c_name};"
            echo "    #[test]"
            echo "    fn ${snake}_can_construct() {"
            echo "        let _ = ${c_name}::new();"
            echo "    }"
        done
        echo "}"
    } >> "${m_dir}/mod.rs"
done

echo "  [OK] rust 生成完成: $LANG_DIR/"

# ---------- 实际调 cargo 验证 ----------
if command -v cargo >/dev/null 2>&1; then
    echo ""
    echo "  ▶ cargo check ..."
    if (cd "$LANG_DIR" && cargo check --quiet 2>&1); then
        echo "  [OK] cargo check 通过"
    else
        echo "  [FAIL] cargo check 失败（生成的代码无法编译）" >&2
        exit 1
    fi
    echo "  ▶ cargo test --no-run ..."
    if (cd "$LANG_DIR" && cargo test --no-run --quiet 2>&1); then
        echo "  [OK] cargo test --no-run 通过"
    else
        echo "  [WARN] cargo test --no-run 失败（不影响主流程，跳过）" >&2
    fi
else
    echo "  [WARN] cargo 未安装，跳过编译验证"
fi